version: "3"
services:
  web:
    build: 
      context: BlogAnalyzerWeb/.
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
