version: "3"
services:
  web:
    build: BlogAnalyzerWeb/.
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
